#!/bin/bash
#Script for Containers

#commands to check whether lxd is exist on our system or not
which lxd > /dev/null

if [ $? -ne 0 ]; then
  #installation of lxd
  echo "Installing lxd -Check for the password prompt"
  sudo snap install lxd
  if [ $? -ne 0 ]; then
  #If installation fails
  echo"Failed to install lxd software"
  exit
 fi
fi

#Creating lxdbr0 interface if it is not found.
ls /sys/class/net | grep -w "lxdbr0" > /dev/null

if [ $? -ne 0 ]; then
	echo "Initializing lxd"
	lxd init --auto > /dev/null
	if [ $? -ne 0 ]; then
	
		echo "lxd initialization failed. Ending script execution"
		exit 1
	fi
fi


#Creating a container running Ubuntu server named COMP2101-S22 
lxc list | grep -w "COMP2101-S22" > /dev/null

if [ $? -ne 0 ]; then
	echo " COMP2101-S22 as Ubuntu 20.04 server craetion successful"
	lxc launch ubuntu:20.04 COMP2101-S22
	if [ $? -ne 0 ]; then
	
		echo "Container creation unsuccessful.  script execution end"
		exit 1
	fi	
	while [ $(lxc list | grep -w "COMP2101-S22" | awk '{print $6}') = "|" ]; do
		sleep 10
	done
fi
# After checking the existence, add the name COMP2101-S22 with the container’s IP address in /etc/hosts.

grep -w "COMP2101-S22" /etc/hosts > /dev/null

if [ $? -ne 0 ]; then
	##VARIABLES##
	ip=$(lxc list | grep -w "COMP2101-S22" | awk '{print $6}')
	hostname="COMP2101-S22"
	#############
	echo "Added COMP2101-S22 container to /etc/hosts"
	sudo sed -i.bkp " 2a $ip\t$hostname " /etc/hosts
	if [ $? -ne 0 ]; then
	# if  fails then it shows a message and exits
		echo " failed.  script execution ended"
		exit 1
	fi
fi

#Installing Apache2 in container after checking the existance
lxc exec COMP2101-S22 -- which apache2 > /dev/null

if [ $? -ne 0 ]; then
	echo "Installing apache on container COMP2101-S22"
	lxc exec COMP2101-S22 -- apt install apache2 -y > /dev/null
	if [ $? -ne 0 ]; then
	
		echo "Apache installation failed.  script execution End"
		exit 1
	fi
fi

#Installing curl if it is not there.
which curl > /dev/null
# if not there then the installation of curl will take place
if [ $? -ne 0 ]; then
	sudo apt install curl -y > /dev/null
	if [ $? -ne 0 ]; then
	
		echo "Curl installation failed.  script execution End"
		exit 1
	fi
fi
#Retrieving information from web service and notifying the user about success or failure.

echo "Checking default web page retrieval from container COMP2101-S22"
curl http://COMP2101-S22 > /dev/null

if [ $? -ne 0 ]; then
	echo "Default web page retrieval was unsuccessful"
else
	echo "Default web page retrieval was successful"
fi
exit
